// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USElections.Data.Models;

/// <summary>
/// Table containing events held by the Charlotte office.
/// </summary>
public partial class Event
{
    public int EventId { get; set; }

    public int EventTypeId { get; set; }

    public string EventName { get; set; }

    public DateOnly EventDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public virtual EventType EventType { get; set; }
}