// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USElections.Data.Models;

/// <summary>
/// Table containing types of events held by the Charlotte office.
/// </summary>
public partial class EventType
{
    public int EventTypeId { get; set; }

    public string EventTypeName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}